"""fix: change address-model

Revision ID: 09ba515b361d
Revises: 9f33e980556b
Create Date: 2022-04-26 12:44:51.258069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ba515b361d'
down_revision = '9f33e980556b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_user_id_key', 'address', type_='unique')
    op.drop_constraint('address_user_id_fkey', 'address', type_='foreignkey')
    op.drop_column('address', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('address_user_id_fkey', 'address', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint('address_user_id_key', 'address', ['user_id'])
    # ### end Alembic commands ###
