"""empty message

Revision ID: 0a8b53e63c00
Revises: ec07862cbe2c
Create Date: 2022-04-30 18:58:02.220331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8b53e63c00'
down_revision = 'ec07862cbe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('patient_code', sa.String(), nullable=False))
    op.drop_column('patients', 'cpf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('patients', 'patient_code')
    # ### end Alembic commands ###
