"""fix patient

Revision ID: 0caee86e0b73
Revises: 59e1de71288d
Create Date: 2022-04-22 14:25:18.859529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caee86e0b73'
down_revision = '59e1de71288d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('hospitalization_date', sa.Date(), nullable=True))
    op.drop_column('patients', 'hospitalizatio_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('hospitalizatio_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'hospitalization_date')
    # ### end Alembic commands ###
