"""refactore User model

Revision ID: 177c769209cd
Revises: 30313e0d33b4
Create Date: 2022-04-26 08:42:42.744130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177c769209cd'
down_revision = '30313e0d33b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registro', sa.String(), nullable=False))
    op.add_column('users', sa.Column('funcao', sa.String(), nullable=False))
    op.drop_constraint('users_crm_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['registro'])
    op.drop_column('users', 'crm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crm', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_unique_constraint('users_crm_key', 'users', ['crm'])
    op.drop_column('users', 'funcao')
    op.drop_column('users', 'registro')
    # ### end Alembic commands ###
