"""empty message

Revision ID: 1d78c7b97ae0
Revises: 2e495c85a5ec
Create Date: 2022-04-26 21:28:00.031899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d78c7b97ae0'
down_revision = '2e495c85a5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'owner_id')
    # ### end Alembic commands ###
