"""Allow table users_workspaces

Revision ID: 30313e0d33b4
Revises: 22dcfd86535d
Create Date: 2022-04-26 07:30:46.708726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30313e0d33b4'
down_revision = '22dcfd86535d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_workspaces',
    sa.Column('users_workspaces_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('users_workspaces_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_workspaces')
    # ### end Alembic commands ###
