"""fix: change name user model

Revision ID: 3d44774e5f88
Revises: 09ba515b361d
Create Date: 2022-04-26 13:28:46.196046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d44774e5f88'
down_revision = '09ba515b361d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession_code', sa.String(), nullable=False))
    op.add_column('users', sa.Column('profession', sa.String(), nullable=False))
    op.drop_constraint('users_registro_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['profession_code'])
    op.drop_column('users', 'registro')
    op.drop_column('users', 'funcao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('funcao', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('registro', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_registro_key', 'users', ['registro'])
    op.drop_column('users', 'profession')
    op.drop_column('users', 'profession_code')
    # ### end Alembic commands ###
