"""implements Address model

Revision ID: 58f330743e48
Revises: 8cb58613d025
Create Date: 2022-04-26 11:31:15.671719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f330743e48'
down_revision = '8cb58613d025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('number_house', sa.String(), nullable=False),
    sa.Column('complement', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
