"""implements delete-cascade

Revision ID: 7c23717dbcb8
Revises: 3d44774e5f88
Create Date: 2022-04-26 20:04:03.439023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c23717dbcb8'
down_revision = '3d44774e5f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'workspaces', ['workspace_id'], ['workspace_id'])
    op.drop_constraint('users_address_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'address', ['address_id'], ['address_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_address_id_fkey', 'users', 'address', ['address_id'], ['address_id'])
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'workspace_id')
    # ### end Alembic commands ###
