"""fix:type Hospitarization_date and birth_date, not null cpf, cascade delete delete address

Revision ID: 87266f0b647a
Revises: c13dcaca6f02
Create Date: 2022-04-28 11:10:15.074581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87266f0b647a'
down_revision = 'c13dcaca6f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('internation', sa.Boolean(), nullable=True))
    op.alter_column('patients', 'hospitalization_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('patients', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'birth_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'birth_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('patients', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'hospitalization_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('patients', 'internation')
    # ### end Alembic commands ###
