"""add owner_id to workspace model

Revision ID: 8cb58613d025
Revises: 177c769209cd
Create Date: 2022-04-26 09:36:34.150485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb58613d025'
down_revision = '177c769209cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'owner_id')
    # ### end Alembic commands ###
