"""fix: chenge user-model FK-address_id

Revision ID: 9f33e980556b
Revises: f524c3cc9412
Create Date: 2022-04-26 12:15:39.094162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f33e980556b'
down_revision = 'f524c3cc9412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['address_id'])
    op.create_foreign_key(None, 'users', 'address', ['address_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###
