"""fix : delete cascade FK user-model

Revision ID: c80d30a58cba
Revises: 1d78c7b97ae0
Create Date: 2022-04-27 13:24:00.738313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80d30a58cba'
down_revision = '1d78c7b97ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_address_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'address', ['address_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_address_id_fkey', 'users', 'address', ['address_id'], ['address_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
