"""create workspace table

Revision ID: da0f387530d1
Revises: 73c51e744222
Create Date: 2022-04-25 10:10:23.928062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0f387530d1'
down_revision = '73c51e744222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datas', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datas', 'patients', ['patient_id'], ['patient_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datas', type_='foreignkey')
    op.drop_column('datas', 'patient_id')
    # ### end Alembic commands ###
