"""fix: deleted FK workspace-model

Revision ID: e7244e6c78e4
Revises: 7c23717dbcb8
Create Date: 2022-04-26 20:32:32.312546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7244e6c78e4'
down_revision = '7c23717dbcb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workspaces', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('workspaces', 'local',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_constraint('workspaces_owner_id_fkey', 'workspaces', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('workspaces_owner_id_fkey', 'workspaces', 'users', ['owner_id'], ['user_id'])
    op.alter_column('workspaces', 'local',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('workspaces', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
