"""fix: comment relation

Revision ID: ec07862cbe2c
Revises: 4d957e7cd9fe
Create Date: 2022-04-30 13:38:23.231243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec07862cbe2c'
down_revision = '4d957e7cd9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_time', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_data_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'categories', ['category_id'], ['category_id'])
    op.create_foreign_key(None, 'comments', 'patients', ['patient_id'], ['patient_id'])
    op.drop_column('comments', 'data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('data_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_data_id_fkey', 'comments', 'datas', ['data_id'], ['data_id'])
    op.drop_column('comments', 'category_id')
    op.drop_column('comments', 'patient_id')
    op.drop_column('comments', 'date_time')
    # ### end Alembic commands ###
