"""fix: deleted attribute city

Revision ID: f524c3cc9412
Revises: fbc40d0f0380
Create Date: 2022-04-26 12:08:39.319669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f524c3cc9412'
down_revision = 'fbc40d0f0380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
