"""implements FK-user Adress

Revision ID: fbc40d0f0380
Revises: 58f330743e48
Create Date: 2022-04-26 12:00:41.378804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc40d0f0380'
down_revision = '58f330743e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'address', ['user_id'])
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='unique')
    op.drop_column('address', 'user_id')
    # ### end Alembic commands ###
