from .geral_exceptions import InvalidInput


class InvalidCEP(InvalidInput): ...
class InvalidStreet(InvalidInput):...
class InvalidNumberHouse(InvalidInput):...
class InvalidComplement(InvalidInput):...
