from .geral_exceptions import InvalidInput, IncorrectField


class InvalidName(InvalidInput):...
class InvalidGender(InvalidInput):...
class InvalidHospitalizationDate(IncorrectField):...
class InvalidCPF(InvalidInput):...
class InvalidProfession(InvalidInput):...
class InvalidMaritalStatus(InvalidInput):...
class InvalidResponsableGuardina(InvalidInput):...
class InvalidResponsableContact(InvalidInput):...
class InternationError(IncorrectField):...
class InvalidBirthdate(IncorrectField):...
