from .geral_exceptions import InvalidInput, InvalidId, IncorrectField


class InvalidTag(InvalidInput):...
class InvalidDataId(InvalidId):...
class InvalidPatientId(InvalidId):...
class AlertTagError(IncorrectField):...